import type { MenuItem } from '@/lib/shopify/types';

// Navigation aligned with CDC V3 Lean — 8 top-level categories
// All URLs use /collections/[handle]

export const mainNavigation: MenuItem[] = [
  {
    id: 'outils-electroportatifs',
    title: 'Outils électroportatifs',
    url: '/collections/outils-electroportatifs',
    image: '/categories/outils-electroportatifs.png',
    items: [
      {
        id: 'percage-et-burinage',
        title: 'Perçage et burinage',
        url: '/collections/percage-et-burinage',
        items: [
          { id: 'carottage', title: 'Carottage', url: '/collections/carottage' },
          { id: 'demolisseurs', title: 'Démolisseurs', url: '/collections/demolisseurs' },
          { id: 'perceuses-a-percussion', title: 'Perceuses à percussion', url: '/collections/perceuses-a-percussion' },
          { id: 'perceuses-magnetiques', title: 'Perceuses magnétiques', url: '/collections/perceuses-magnetiques' },
          { id: 'perceuses-visseuses', title: 'Perceuses visseuses', url: '/collections/perceuses-visseuses' },
          { id: 'sds-max', title: 'SDS Max', url: '/collections/sds-max' },
          { id: 'sds-plus', title: 'SDS Plus', url: '/collections/sds-plus' },
        ],
      },
      {
        id: 'vissage',
        title: 'Vissage',
        url: '/collections/vissage',
        items: [
          { id: 'boulonneuses', title: 'Boulonneuses à chocs', url: '/collections/boulonneuses-a-chocs' },
          { id: 'cles-a-cliquet', title: 'Clés à cliquet', url: '/collections/cles-a-cliquet' },
          { id: 'cloueurs', title: 'Cloueurs', url: '/collections/cloueurs' },
          { id: 'riveteuse', title: 'Riveteuse', url: '/collections/riveteuse' },
          { id: 'visseuses', title: 'Visseuses', url: '/collections/visseuses' },
          { id: 'visseuses-a-chocs', title: 'Visseuses à chocs', url: '/collections/visseuses-a-chocs' },
        ],
      },
      {
        id: 'meuleuses-et-polisseuses',
        title: 'Meuleuses et polisseuses',
        url: '/collections/meuleuses-et-polisseuses',
        items: [
          { id: 'meuleuses-115', title: 'Meuleuses 115 mm', url: '/collections/meuleuses-115-mm' },
          { id: 'meuleuses-125', title: 'Meuleuses 125 mm', url: '/collections/meuleuses-125-mm' },
          { id: 'meuleuses-150', title: 'Meuleuses 150 mm', url: '/collections/meuleuses-150-mm' },
          { id: 'meuleuses-180', title: 'Meuleuses 180 mm', url: '/collections/meuleuses-180-mm' },
          { id: 'meuleuses-230', title: 'Meuleuses 230 mm', url: '/collections/meuleuses-230-mm' },
          { id: 'meuleuses-d-angle', title: "Meuleuses d'angle", url: '/collections/meuleuses-d-angle' },
          { id: 'meuleuses-droites', title: 'Meuleuses droites', url: '/collections/meuleuses-droites' },
          { id: 'outils-rotatifs', title: 'Outils rotatifs', url: '/collections/outils-rotatifs' },
          { id: 'polisseuses', title: 'Polisseuses', url: '/collections/polisseuses' },
        ],
      },
      {
        id: 'sciage-et-decoupage',
        title: 'Sciage et découpage',
        url: '/collections/sciage-et-decoupage',
        items: [
          { id: 'affleureuse', title: 'Affleureuse', url: '/collections/affleureuse' },
          { id: 'cisailles', title: 'Cisailles', url: '/collections/cisailles' },
          { id: 'coupe-tubes', title: 'Coupe tubes', url: '/collections/coupe-tubes' },
          { id: 'multitools', title: 'Multitools', url: '/collections/multitools' },
          { id: 'rabots', title: 'Rabots', url: '/collections/rabots' },
          { id: 'rainureuses', title: 'Rainureuses', url: '/collections/rainureuses' },
          { id: 'scies-a-ruban', title: 'Scies à ruban', url: '/collections/scies-a-ruban' },
          { id: 'scies-circulaires', title: 'Scies circulaires', url: '/collections/scies-circulaires' },
          { id: 'scies-radiales', title: 'Scies radiales et support', url: '/collections/scies-radiales-et-support' },
          { id: 'scies-sabres', title: 'Scies sabres', url: '/collections/scies-sabres' },
          { id: 'scies-sauteuses', title: 'Scies sauteuses', url: '/collections/scies-sauteuses' },
          { id: 'tronconneuses', title: 'Tronçonneuses', url: '/collections/tronconneuses' },
        ],
      },
      {
        id: 'sertissage',
        title: 'Sertissage et câblage',
        url: '/collections/sertissage',
        items: [
          { id: 'cable-stripping', title: 'Cable stripping', url: '/collections/cable-stripping' },
          { id: 'connexion-de-cables', title: 'Connexion de câbles', url: '/collections/connexion-de-cable' },
          { id: 'coupe-cables', title: 'Coupe câbles', url: '/collections/coupe-cables' },
          { id: 'coupe-rail', title: 'Coupe rail de supportage', url: '/collections/coupe-rail-de-supportage' },
          { id: 'coupe-tige-filetee', title: 'Coupe tige filetée', url: '/collections/coupe-tige-filetee' },
          { id: 'emporte-piece', title: 'Emporte-pièce', url: '/collections/emporte-piece' },
          { id: 'expandeurs', title: 'Expandeurs', url: '/collections/expandeurs' },
          { id: 'pompe-hydraulique', title: 'Pompe hydraulique', url: '/collections/pompe-hydraulique' },
          { id: 'sertisseuse-electricite', title: 'Sertisseuse électricité', url: '/collections/sertisseuse-electricite' },
          { id: 'sertisseuse-plomberie', title: 'Sertisseuse plomberie', url: '/collections/sertisseuse-plomberie' },
          { id: 'tire-fils', title: 'Tire-fils', url: '/collections/tire-fils' },
        ],
      },
      {
        id: 'beton',
        title: 'Béton',
        url: '/collections/beton',
        items: [
          { id: 'compactage', title: 'Compactage', url: '/collections/compactage' },
          { id: 'regles-vibrantes', title: 'Règles vibrantes', url: '/collections/regles-vibrantes' },
          { id: 'vibration-beton', title: 'Vibration béton', url: '/collections/vibration-beton' },
        ],
      },
      {
        id: 'poncage',
        title: 'Ponçage',
        url: '/collections/poncage',
        items: [
          { id: 'ponceuse', title: 'Ponceuse', url: '/collections/ponceuse' },
        ],
      },
      {
        id: 'autres',
        title: 'Autres',
        url: '/collections/autres-outils',
        items: [
          { id: 'compresseur', title: 'Compresseur', url: '/collections/compresseur' },
          { id: 'decapeur-thermique', title: 'Décapeur thermique', url: '/collections/decapeur-thermique' },
          { id: 'fer-a-souder', title: 'Fer à souder', url: '/collections/fer-a-souder' },
          { id: 'filiere', title: 'Filière', url: '/collections/filiere' },
          { id: 'malaxeur', title: 'Malaxeur', url: '/collections/malaxeur' },
          { id: 'material-handling', title: 'Material Handling', url: '/collections/material-handling' },
          { id: 'pistolets-a-colle', title: 'Pistolets à colle', url: '/collections/pistolets-a-colle' },
          { id: 'pompe-a-vide', title: 'Pompe à vide', url: '/collections/pompe-a-vide' },
          { id: 'pompe-de-transfert', title: 'Pompe de transfert', url: '/collections/pompe-de-transfert' },
          { id: 'pompes-a-graisse', title: 'Pompes à graisse', url: '/collections/pompes-a-graisse' },
          { id: 'radios', title: 'Radios', url: '/collections/radios' },
          { id: 'rectifieuse', title: 'Rectifieuse à pneumatiques', url: '/collections/rectifieuse-a-pneumatiques' },
          { id: 'souffleurs-et-ventilateurs', title: 'Souffleurs et ventilateurs', url: '/collections/souffleurs-et-ventilateurs' },
        ],
      },
    ],
  },
  {
    id: 'batteries-chargeurs',
    title: 'Batteries, chargeurs et générateur',
    url: '/collections/batteries-chargeurs-et-generateurs',
    image: '/categories/batteries-chargeurs.png',
    items: [
      { id: 'batteries', title: 'Batteries', url: '/collections/batteries' },
      { id: 'batteries-et-chargeurs', title: 'Batteries et chargeurs', url: '/collections/batteries-et-chargeurs' },
      { id: 'chargeurs', title: 'Chargeurs', url: '/collections/chargeurs' },
      { id: 'generateur', title: 'Générateur', url: '/collections/generateur' },
    ],
  },
  {
    id: 'aspirateurs',
    title: 'Aspirateurs',
    url: '/collections/aspirateurs',
    image: '/categories/aspirateurs.png',
    items: [
      { id: 'aspirateurs-classe-l', title: 'Classe L', url: '/collections/aspirateurs-classe-l' },
      { id: 'aspirateurs-classe-m', title: 'Classe M', url: '/collections/aspirateurs-classe-m' },
    ],
  },
  {
    id: 'eclairage',
    title: 'Éclairage',
    url: '/collections/eclairage',
    image: '/categories/eclairage.png',
    items: [
      { id: 'torches', title: 'Torches', url: '/collections/torches' },
      { id: 'lampes-frontales', title: 'Lampes frontales', url: '/collections/lampes-frontales' },
      { id: 'eclairage-portatif', title: 'Éclairage portatif', url: '/collections/eclairage-portatif' },
      { id: 'eclairage-de-site', title: 'Éclairage de site', url: '/collections/eclairage-de-site' },
      { id: 'tour-eclairage', title: "Tour d'éclairage", url: '/collections/tour-d-eclairage' },
      { id: 'accessoires-eclairage', title: 'Accessoires', url: '/collections/accessoires-eclairage' },
    ],
  },
  {
    id: 'instruments-de-mesure',
    title: 'Instruments de mesure',
    url: '/collections/instruments-de-mesure',
    image: '/categories/instruments-mesure.png',
    items: [
      {
        id: 'diagnostic-et-inspection',
        title: 'Diagnostic et inspection',
        url: '/collections/diagnostic-et-inspection',
        items: [
          { id: 'cameras-inspection', title: "Caméras d'inspection", url: '/collections/cameras-d-inspection' },
          { id: 'detecteur', title: 'Détecteur', url: '/collections/detecteur' },
        ],
      },
      {
        id: 'lasers',
        title: 'Lasers',
        url: '/collections/lasers',
        items: [
          { id: 'lasers-lignes', title: 'Lasers lignes', url: '/collections/lasers-lignes' },
          { id: 'lasers-rotatifs', title: 'Lasers rotatifs', url: '/collections/lasers-rotatifs' },
        ],
      },
      {
        id: 'outils-de-test-et-mesure',
        title: 'Outils de test et mesure',
        url: '/collections/outils-de-test-et-mesure',
        items: [
          { id: 'lasremetres', title: 'Lasermètres', url: '/collections/lasremetres' },
          { id: 'pistolets-thermiques', title: 'Pistolets à mesure thermique', url: '/collections/pistolets-a-mesure-thermique' },
          { id: 'testeurs-electriques', title: 'Testeurs électriques', url: '/collections/testeurs-electriques' },
        ],
      },
    ],
  },
  {
    id: 'epi-vetements',
    title: 'EPI & Vêtements',
    url: '/collections/epi-vetements',
    image: '/categories/epi.png',
    items: [
      {
        id: 'protection',
        title: 'Protection',
        url: '/collections/epi-vetements',
        items: [
          { id: 'casques-protection', title: 'Casques de protection', url: '/collections/casques-de-protection' },
          { id: 'chaussures-securite', title: 'Chaussures de sécurité', url: '/collections/chaussures-de-securite' },
          { id: 'lunettes-protection', title: 'Lunettes de protection', url: '/collections/lunettes-de-protection' },
          { id: 'gants', title: 'Gants', url: '/collections/gants' },
        ],
      },
      {
        id: 'vetements-chauffants',
        title: 'Vêtements chauffants M12™',
        url: '/collections/vetements-chauffants',
        items: [
          { id: 'vestes-chauffantes', title: 'Vestes chauffantes', url: '/collections/vestes-chauffantes' },
          { id: 'hoodies-chauffants', title: 'Hoodies chauffants', url: '/collections/hoodies-chauffants' },
        ],
      },
    ],
  },
  {
    id: 'exterieurs-espaces-verts',
    title: 'Extérieurs & espaces verts',
    url: '/collections/exterieurs-et-espaces-verts',
    image: '/categories/exterieurs-espaces-verts.png',
    items: [
      {
        id: 'tronconneuses-et-elagage',
        title: 'Tronçonneuses et élagage',
        url: '/collections/tronconneuses',
        items: [
          { id: 'elagueuses', title: 'Élagueuses', url: '/collections/elagueuses' },
          { id: 'perche-d-elagage', title: "Perche d'élagage", url: '/collections/perche-d-elagage' },
          { id: 'tronconneuses', title: 'Tronçonneuses', url: '/collections/tronconneuses' },
          { id: 'tronconneuses-elagage', title: 'Tronçonneuses élagage', url: '/collections/tronconneuses-elagage' },
        ],
      },
      {
        id: 'debroussaillage-et-taille',
        title: 'Débroussaillage et taille',
        url: '/collections/debroussaillage-et-nettoyage',
        items: [
          { id: 'debroussailleuses', title: 'Débroussailleuses', url: '/collections/debroussailleuses' },
          { id: 'secateurs', title: 'Sécateurs', url: '/collections/secateurs' },
          { id: 'taille-haies', title: 'Taille-haies', url: '/collections/taille-haies' },
          { id: 'taille-haies-sur-perche', title: 'Taille-haies sur perche', url: '/collections/taille-haies-sur-perche' },
        ],
      },
      {
        id: 'entretien-sols-pelouses',
        title: 'Entretien des sols et pelouses',
        url: '/collections/entretien-des-sols-des-pelouses-et-des-terrains',
        items: [
          { id: 'coupe-bordures', title: 'Coupe-bordures', url: '/collections/coupe-bordures' },
          { id: 'fraise-a-neige', title: 'Fraise à neige', url: '/collections/fraise-a-neige' },
          { id: 'pulverisateurs', title: 'Pulvérisateurs', url: '/collections/pulverisateurs' },
          { id: 'souffleurs', title: 'Souffleurs', url: '/collections/souffleurs' },
          { id: 'tondeuse-a-gazon', title: 'Tondeuse à gazon', url: '/collections/tondeuse-a-gazon' },
        ],
      },
      { id: 'combi-systeme-quik-lok', title: 'Combi-système QUIK-LOK', url: '/collections/combi-systeme-quik-lok' },
    ],
  },
  {
    id: 'assainissement',
    title: 'Assainissement et nettoyage des canalisations',
    url: '/collections/assainissement-et-nettoyage',
    image: '/categories/assainissement.png',
    items: [
      { id: 'deboucheur-sections', title: 'Déboucheur à sections', url: '/collections/deboucheur-a-sections' },
      { id: 'deboucheur-sections-tambours', title: 'Déboucheur à sections et à tambours', url: '/collections/deboucheur-a-sections-et-a-tambours' },
      { id: 'deboucheur-automatique', title: 'Déboucheur automatique haute vitesse', url: '/collections/deboucheur-automatique-haute-vitesse' },
      { id: 'deboucheurs-tambours', title: 'Déboucheurs à tambours', url: '/collections/deboucheurs-a-tambours' },
    ],
  },
];
